[package]
name = "attestation-meta"
version = "0.0.0"
authors = ["andrei-marinica <andrei.marinica@elrond.com>"]
edition = "2021"
publish = false

[dependencies.attestation]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.45.0"
