name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  contracts:
    name: Contracts
    uses: multiversx/mx-sc-actions/.github/workflows/contracts.yml@v1
    with:
      rust-toolchain: nightly-2022-12-08
      vmtools-version: v1.4.60
      extra-build-args: --ignore-eei-checks
      wasm-tests-args: --features run-go-tests
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
